---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keylime-server
  labels:
    helm.sh/chart: keylime-v0.0.1
    app.kubernetes.io/name: keylime
    app.kubernetes.io/instance: keylime
    app.kubernetes.io/version: "v6.3.2"
    app.kubernetes.io/managed-by: Helm
    control-plane: keylime-server
subjects:
- kind: ServiceAccount
  name: keylime-server
  namespace: keylime
roleRef:
  kind: Role
  name: keylime-server
  apiGroup: rbac.authorization.k8s.io
