---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keylime-server
  labels:
    helm.sh/chart: keylime-v0.0.1
    app.kubernetes.io/name: keylime
    app.kubernetes.io/instance: keylime
    app.kubernetes.io/version: "v6.3.2"
    app.kubernetes.io/managed-by: Helm
    control-plane: keylime-server
rules:
  # Needed to watch and load configuration and secret data.
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "update", "watch"]
