---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: keylime-v0.0.1
    app.kubernetes.io/name: keylime
    app.kubernetes.io/instance: keylime
    app.kubernetes.io/version: "v6.3.2"
    app.kubernetes.io/managed-by: Helm
    control-plane: keylime-server
  name: keylime-server
