---
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: keylime-v0.0.1
    app.kubernetes.io/name: keylime
    app.kubernetes.io/instance: keylime
    app.kubernetes.io/version: "v6.3.2"
    app.kubernetes.io/managed-by: Helm
    control-plane: keylime-server
  name: keylime-server
spec:
  type: ClusterIP
  ports:
  - name: verifier-http
    port: 8881
    protocol: TCP
    targetPort: 8881
  - name: registrar-http
    port: 8890
    protocol: TCP
    targetPort: 8890
  - name: registrar-https
    port: 8891
    protocol: TCP
    targetPort: 8891
  selector:
    app.kubernetes.io/name: keylime
    app.kubernetes.io/instance: keylime
    control-plane: keylime-server
